#!/usr/bin/env node
/**
 * Generates the downloadable CV, one PDF per language, into static/files/.
 *
 *   node scripts/make-cv.mjs            all three languages
 *   node scripts/make-cv.mjs en         just one
 *
 * WHY IT READS data/ INSTEAD OF BEING WRITTEN BY HAND
 *
 * Every role, date, bullet, degree and certification comes from the same YAML the
 * website renders, loaded with the same `loadLang` the checkers use. The CV
 * therefore cannot contradict the site: there is no second copy of the career
 * history to drift out of step. That is the property the cross-language checker
 * exists to protect, applied to a second output format.
 *
 * It also matters for privacy. `check-pii` skips .pdf by extension, so it can
 * never look inside this output. The guarantee that the CV carries no phone
 * number or postal address is not a scan of the PDF — it is that every string in
 * it originates in data/, which IS scanned. The CV's own labels live in
 * data/<lang>/cv.yaml for exactly that reason.
 *
 * WHY PDFKIT, AFTER TWO OTHER ROUTES FAILED
 *
 * First attempt was Chromium's --print-to-pdf, which would have allowed real print
 * CSS and the site's own Mulish typeface. Edge 151 is installed and it does not
 * work on this machine: headless startup logs "Network service crashed or was
 * terminated" and produces no PDF, for a trivial one-line HTML file as much as for
 * the real one. The corporate security stack that already intercepts credly.com
 * appears to take the network service down with it. Not worth fighting.
 *
 * Emitting raw PDF operators by hand — the approach make-background.mjs uses for
 * the hero image — is possible but needs font metrics, word wrapping and page
 * breaking written from scratch.
 *
 * So: pdfkit, added to scripts/package.json. That file is hand-maintained and
 * exists precisely so dependencies survive — its own description says so, because
 * the ROOT package.json is regenerated by `hugo mod npm pack` on every install.
 *
 * Typeface is Helvetica, one of the PDF base-14, so nothing is embedded and the
 * file stays a few KB. @fontsource ships Mulish only as woff/woff2 and pdfkit
 * embeds TTF/OTF, so matching the site's typeface would mean writing a woff→sfnt
 * repacker. Helvetica on a CV is unremarkable in the good sense.
 *
 * The PDFs are committed. No build depends on running this.
 */
import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import PDFDocument from 'pdfkit'
import { REPO, LANGS, loadLang, green, yellow, red } from './lib.mjs'

const OUT_DIR = path.join(REPO, 'static/files')

// A4 in points, with margins that leave a 2-page CV room to breathe.
const PAGE = { size: 'A4', margins: { top: 42, bottom: 40, left: 46, right: 46 } }
const INK = '#16202c'
const MUTED = '#5b6976'
const RULE = '#d3dae1'
const ACCENT = '#0891b2' // the site's accent, from the theme's variables.scss

const only = process.argv[2]
const targets = only ? [only] : LANGS
for (const l of targets) {
  if (!LANGS.includes(l)) {
    console.error(red(`unknown language "${l}" — expected one of ${LANGS.join(', ')}`))
    process.exit(1)
  }
}

/**
 * Everything a base-14 font can encode: WinAnsi, which is Latin-1 plus the
 * printable 0x80-0x9F block. Em dash, en dash, curly quotes, bullet and ellipsis
 * are all in there — they were checked, not assumed.
 */
const WINANSI_EXTRA = '€‚ƒ„…†‡ˆ‰Š‹ŒŽ‘’“”•–—˜™š›œžŸ'
const encodable = (ch) => {
  const c = ch.codePointAt(0)
  if (c === 0x0a) return true
  if (c >= 0x20 && c <= 0x7e) return true
  if (c >= 0xa0 && c <= 0xff) return true
  return WINANSI_EXTRA.includes(ch)
}

/**
 * Characters the data uses that WinAnsi has no code for.
 *
 * Found the hard way: "Risk Analyst (Intern → Junior → Analyst)" came out as
 * "Intern !’ Junior". pdfkit does not drop an unencodable character — it emits the
 * two halves of its code point as separate bytes, so U+2192 became 0x21 0x92,
 * which renders as an exclamation mark and a curly quote. Silent corruption, and
 * the kind you only notice by reading the output.
 */
const SUBSTITUTIONS = [[/→/g, '->'], [/←/g, '<-'], [/[‐-–]/g, '-']]

/** Fails loudly rather than corrupting: a new character in the data that the font
 *  cannot encode stops the build instead of printing garbage into a published CV. */
function winAnsi (s) {
  let out = String(s ?? '')
  for (const [re, to] of SUBSTITUTIONS) out = out.replace(re, to)
  const bad = [...out].filter((ch) => !encodable(ch))
  if (bad.length) {
    throw new Error(
      `cannot encode ${[...new Set(bad)].map((c) => `"${c}" (U+${c.codePointAt(0).toString(16).toUpperCase().padStart(4, '0')})`).join(', ')} ` +
      `in a base-14 PDF font.\n  in: ${out.slice(0, 120)}\n  ` +
      'Add a mapping to SUBSTITUTIONS in scripts/make-cv.mjs, or change the wording in data/.')
  }
  return out
}

/** Markdown inline -> plain text, then WinAnsi-safe. The data files use
 *  [label](url) so the site can link out; a printed page cannot follow a link, so
 *  only the label survives. */
const plain = (s) => winAnsi(String(s ?? '')
  .replace(/\[([^\]]+)\]\([^)]*\)/g, '$1')
  .replace(/\*\*([^*]+)\*\*/g, '$1')
  .replace(/\*([^*]+)\*/g, '$1'))

/**
 * The theme already ships `present` and `resume` in all three languages.
 * Re-translating them here would be a second copy free to drift from what the
 * navbar and the section headings say, so they are read from the theme module.
 */
function themeI18n (lang, key) {
  const roots = [
    path.join(os.homedir(), 'AppData/Local/hugo_cache/modules/filecache/modules/pkg/mod'),
    path.join(os.homedir(), 'go/pkg/mod')
  ]
  // The module sits two levels down, as github.com/hugo-toha/toha/v4@v4.16.0, so a
  // single readdir of hugo-toha finds only "toha" and misses the i18n directory
  // entirely. That is not hypothetical: the first version of this function looked
  // one level deep, returned null for every language, and the Spanish and
  // Portuguese CVs silently said "Present" instead of "Presente".
  const find = (dir, depth) => {
    if (depth > 3 || !fs.existsSync(dir)) return null
    const direct = path.join(dir, 'i18n', `${lang}.toml`)
    if (fs.existsSync(direct)) return direct
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      if (!e.isDirectory()) continue
      const hit = find(path.join(dir, e.name), depth + 1)
      if (hit) return hit
    }
    return null
  }
  for (const root of roots) {
    const f = find(path.join(root, 'github.com/hugo-toha'), 0)
    if (!f) continue
    const m = fs.readFileSync(f, 'utf8').match(new RegExp(`\\[${key}\\][^[]*other\\s*=\\s*"([^"]*)"`))
    if (m) return m[1]
  }
  return null
}

/** Throws rather than falling back to English. A Spanish CV that says "Present"
 *  is worse than a build that stops and tells you the theme module is missing. */
function requireThemeI18n (lang, key) {
  const v = themeI18n(lang, key)
  if (!v) {
    throw new Error(`could not resolve the theme's "${key}" translation for "${lang}". ` +
      'Run `mise run install` so the Toha module is in the Hugo cache — falling back to ' +
      'English here would put the wrong word in a published CV.')
  }
  return v
}

// Six certifications, named explicitly rather than sliced off the top of the
// list: reordering accomplishments.yaml must not silently change what the CV
// claims. The other five stay on the site, and a line points there.
const CV_CERTS = [
  'Data Engineer Associate',
  'Microsoft Certified: Azure Fundamentals (AZ-900)',
  'Microsoft Power BI Desktop for Business Intelligence',
  "CS50's Introduction to Programming with Python",
  'Data Engineer',
  'SQL Server Database Performance Monitoring and Tuning'
]

function model (lang) {
  const d = loadLang(lang)
  const need = (k) => {
    if (!d[k]) throw new Error(`data/${lang}/${k} is missing`)
    return d[k]
  }
  const cv = need('cv.yaml')
  const author = need('author.yaml')
  const about = need('sections/about.yaml')
  const exp = need('sections/experiences.yaml')
  const edu = need('sections/education.yaml')
  const skills = need('sections/skills.yaml')
  const accs = need('sections/accomplishments.yaml')
  const present = requireThemeI18n(lang, 'present')

  const certs = CV_CERTS.map((n) => {
    const hit = (accs.accomplishments ?? []).find((a) => a.name === n)
    if (!hit) throw new Error(`data/${lang}: certification "${n}" is not in accomplishments.yaml`)
    return hit
  })

  // Every string below goes through winAnsi(), directly or via plain(). That is
  // deliberate rather than defensive: it is the only thing standing between a
  // character the data gains tomorrow and a published CV with garbage in it.
  return {
    cv: {
      headline: winAnsi(cv.headline),
      headings: Object.fromEntries(Object.entries(cv.headings).map(([k, v]) => [k, winAnsi(v)])),
      languages: (cv.languages ?? []).map(winAnsi),
      certificationsNote: winAnsi(cv.certificationsNote),
      footer: winAnsi(cv.footer)
    },
    name: winAnsi(author.name),
    // LinkedIn and GitHub only. No email and no phone: the site omits them by
    // decision, and this file is publicly downloadable, so anything on it is
    // permanently public.
    contact: [
      `linkedin.com/in/${author.contactInfo.linkedin}`,
      `github.com/${author.contactInfo.github}`
    ].join('   ·   '),
    summary: plain(about.summary),
    // Grouped by the site's own filter buttons, skipping "all".
    groups: (skills.buttons ?? [])
      .filter((b) => b.filter !== 'all')
      .map((b) => ({
        name: winAnsi(b.name),
        items: (skills.skills ?? [])
          .filter((s) => (s.categories ?? []).includes(b.filter))
          .map((s) => winAnsi(s.name))
      }))
      .filter((g) => g.items.length),
    jobs: (exp.experiences ?? []).flatMap((c) => (c.positions ?? []).map((p) => ({
      title: winAnsi(p.designation),
      when: winAnsi(`${p.start} – ${p.end ?? present}`),
      where: winAnsi(`${c.company.name} · ${c.company.location}`),
      bullets: (p.responsibilities ?? []).map(plain)
    }))),
    degrees: (edu.degrees ?? []).map((g) => ({
      title: winAnsi(g.name),
      when: winAnsi(g.timeframe),
      where: winAnsi(g.institution.name),
      extra: (g.customSections ?? []).map((s) => plain(s.content)).join(' ')
    })),
    certs: certs.map((c) => ({
      name: winAnsi(c.name),
      org: winAnsi(c.organization.name),
      when: winAnsi(c.timeline ?? '')
    }))
  }
}

function build (lang, m) {
  const doc = new PDFDocument({ ...PAGE, autoFirstPage: true, bufferPages: true })
  const L = PAGE.margins.left
  const W = doc.page.width - PAGE.margins.left - PAGE.margins.right
  const bottom = () => doc.page.height - PAGE.margins.bottom

  const H = (s) => {
    doc.moveDown(0.55)
    doc.font('Helvetica-Bold').fontSize(8).fillColor(MUTED)
      .text(s.toUpperCase(), L, doc.y, { characterSpacing: 1.1, width: W })
    doc.moveDown(0.18)
    doc.moveTo(L, doc.y).lineTo(L + W, doc.y).lineWidth(0.6).strokeColor(RULE).stroke()
    doc.moveDown(0.42)
  }

  /** Measure a block before drawing it, and start a new page if it would split.
   *  This is what keeps a role's heading off the foot of a page with its bullets
   *  orphaned onto the next one. */
  const keepTogether = (height) => {
    if (doc.y + height > bottom()) doc.addPage()
  }

  // --- header ---
  doc.font('Helvetica-Bold').fontSize(21).fillColor(INK).text(m.name, L, doc.y, { width: W })
  doc.moveDown(0.12)
  doc.font('Helvetica-Bold').fontSize(8.6).fillColor(ACCENT).text(m.cv.headline, { width: W })
  doc.moveDown(0.18)
  doc.font('Helvetica').fontSize(8.4).fillColor(MUTED).text(m.contact, { width: W })
  doc.moveDown(0.3)
  doc.moveTo(L, doc.y).lineTo(L + W, doc.y).lineWidth(1.8).strokeColor(ACCENT).stroke()

  // --- summary ---
  H(m.cv.headings.summary)
  doc.font('Helvetica').fontSize(9).fillColor(INK)
    .text(m.summary, L, doc.y, { width: W, align: 'justify', lineGap: 0.6 })

  // --- skills ---
  H(m.cv.headings.skills)
  const labelW = 96
  for (const g of m.groups) {
    const text = g.items.join(' · ')
    const h = Math.max(
      doc.font('Helvetica').fontSize(8.7).heightOfString(text, { width: W - labelW - 8 }),
      doc.font('Helvetica-Bold').fontSize(8.7).heightOfString(g.name, { width: labelW })
    )
    keepTogether(h + 3)
    const y = doc.y
    doc.font('Helvetica-Bold').fontSize(8.7).fillColor(MUTED).text(g.name, L, y, { width: labelW })
    doc.font('Helvetica').fontSize(8.7).fillColor(INK)
      .text(text, L + labelW + 8, y, { width: W - labelW - 8 })
    doc.y = y + h + 2.4
  }

  // --- experience ---
  H(m.cv.headings.experience)
  const usable = doc.page.height - PAGE.margins.top - PAGE.margins.bottom
  for (const j of m.jobs) {
    const titleH = doc.font('Helvetica-Bold').fontSize(10).heightOfString(j.title, { width: W - 92 })
    const whereH = doc.font('Helvetica-Bold').fontSize(8.5).heightOfString(j.where, { width: W })
    const bulletsH = j.bullets.reduce((a, b) =>
      a + doc.font('Helvetica').fontSize(8.9).heightOfString(b, { width: W - 12 }) + 1.1, 0)

    // Prefer keeping the whole role on one page — a role split 3 bullets / 1 looks
    // like an accident. If it is taller than a page that is impossible, so fall
    // back to guaranteeing the heading is never orphaned from its first bullet.
    const whole = titleH + whereH + bulletsH + 12
    const minimum = titleH + whereH +
      (j.bullets[0] ? doc.font('Helvetica').fontSize(8.9).heightOfString(j.bullets[0], { width: W - 12 }) : 0) + 12
    keepTogether(whole <= usable ? whole : minimum)

    const y0 = doc.y
    doc.font('Helvetica-Bold').fontSize(10).fillColor(INK).text(j.title, L, y0, { width: W - 92 })
    doc.font('Helvetica-Bold').fontSize(8.4).fillColor(MUTED)
      .text(j.when, L + W - 92, y0 + 1.5, { width: 92, align: 'right' })
    doc.y = Math.max(doc.y, y0 + doc.font('Helvetica-Bold').fontSize(10).heightOfString(j.title, { width: W - 92 }))
    doc.font('Helvetica-Bold').fontSize(8.5).fillColor(ACCENT).text(j.where, L, doc.y, { width: W })
    doc.moveDown(0.15)
    for (const b of j.bullets) {
      const h = doc.font('Helvetica').fontSize(8.9).heightOfString(b, { width: W - 12 })
      keepTogether(h + 1)
      const y = doc.y
      doc.font('Helvetica-Bold').fontSize(8.9).fillColor(ACCENT).text('·', L + 2, y)
      doc.font('Helvetica').fontSize(8.9).fillColor(INK)
        .text(b, L + 12, y, { width: W - 12, align: 'justify', lineGap: 0.4 })
      doc.y = y + h + 1.1
    }
    doc.moveDown(0.35)
  }

  // --- education ---
  H(m.cv.headings.education)
  for (const g of m.degrees) {
    const h = doc.font('Helvetica-Bold').fontSize(9.6).heightOfString(g.title, { width: W - 92 }) +
      doc.font('Helvetica-Bold').fontSize(8.5).heightOfString(g.where, { width: W }) +
      (g.extra ? doc.font('Helvetica').fontSize(8.5).heightOfString(g.extra, { width: W }) : 0) + 8
    keepTogether(h)
    const y0 = doc.y
    doc.font('Helvetica-Bold').fontSize(9.6).fillColor(INK).text(g.title, L, y0, { width: W - 92 })
    doc.font('Helvetica-Bold').fontSize(8.4).fillColor(MUTED)
      .text(g.when, L + W - 92, y0 + 1.5, { width: 92, align: 'right' })
    doc.font('Helvetica-Bold').fontSize(8.5).fillColor(ACCENT).text(g.where, L, doc.y, { width: W })
    if (g.extra) {
      doc.font('Helvetica-Oblique').fontSize(8.5).fillColor(MUTED).text(g.extra, L, doc.y, { width: W })
    }
    doc.moveDown(0.32)
  }

  // --- certifications ---
  H(m.cv.headings.certifications)
  for (const c of m.certs) {
    const h = doc.font('Helvetica').fontSize(8.9).heightOfString(`${c.name} — ${c.org}`, { width: W - 60 })
    keepTogether(h + 2)
    const y = doc.y
    doc.font('Helvetica-Bold').fontSize(8.9).fillColor(INK).text(c.name, L, y, { width: W - 60, continued: true })
      .font('Helvetica').fillColor(MUTED).text(`  —  ${c.org}`, { continued: false })
    if (c.when) {
      doc.font('Helvetica-Bold').fontSize(8.4).fillColor(MUTED)
        .text(c.when, L + W - 60, y + 0.5, { width: 60, align: 'right' })
    }
    doc.y = y + h + 1.6
  }
  doc.moveDown(0.15)
  doc.font('Helvetica-Oblique').fontSize(8.2).fillColor(MUTED)
    .text(m.cv.certificationsNote, L, doc.y, { width: W })

  // --- languages ---
  H(m.cv.headings.languages)
  doc.font('Helvetica-Bold').fontSize(8.9).fillColor(INK)
    .text((m.cv.languages ?? []).join('     ·     '), L, doc.y, { width: W })

  // --- footer on every page, added after layout so the page count is known ---
  //
  // The footer sits in the bottom margin, below the text area. PDFKit treats any
  // text starting past margins.bottom as an overflow and silently ADDS A PAGE for
  // it — which is how a clean 2-page layout first came out as 6, one extra page
  // per footer written. Zeroing the page's bottom margin for the duration is the
  // documented way to write into that band. It has to be done per page, because
  // each page carries its own margins object.
  const range = doc.bufferedPageRange()
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(range.start + i)
    const keep = doc.page.margins.bottom
    doc.page.margins.bottom = 0
    const y = doc.page.height - 30
    doc.moveTo(L, y - 6).lineTo(L + W, y - 6).lineWidth(0.6).strokeColor(RULE).stroke()
    doc.font('Helvetica').fontSize(7.4).fillColor(MUTED)
      .text(m.cv.footer, L, y, { width: W - 40, lineBreak: false })
    doc.font('Helvetica').fontSize(7.4).fillColor(MUTED)
      .text(`${range.start + i + 1}/${range.count}`, L + W - 40, y, { width: 40, align: 'right' })
    doc.page.margins.bottom = keep
  }

  doc.end()
  return doc
}

fs.mkdirSync(OUT_DIR, { recursive: true })
let bad = 0

for (const lang of targets) {
  const m = model(lang)
  const out = path.join(OUT_DIR, `cv-elton-rodrigues-${lang}.pdf`)
  const doc = build(lang, m)
  const chunks = []
  await new Promise((res, rej) => {
    doc.on('data', (c) => chunks.push(c))
    doc.on('end', res)
    doc.on('error', rej)
  })
  const buf = Buffer.concat(chunks)
  fs.writeFileSync(out, buf)

  const pages = (buf.toString('latin1').match(/\/Type\s*\/Page[^s]/g) ?? []).length
  const kb = (buf.length / 1024).toFixed(1)
  const ok = pages === 2
  if (!ok) bad++
  console.log(`${lang.padEnd(6)} ${path.relative(REPO, out).padEnd(44)} ${kb.padStart(6)} KB  ` +
    (ok ? green('2 pages') : yellow(`${pages} pages — expected 2`)))
}

if (bad) {
  console.log(yellow('\nSome CVs are not 2 pages. Spanish and Portuguese run longer than English;'))
  console.log(yellow('adjust the font sizes at the top of this file rather than cutting content.'))
}
