name: PR Workflows

# Run action on pull request event
on: [pull_request]

jobs:
  # Verify the site builds
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout to the commit that has been pushed
      - uses: actions/checkout@v7

      # Setup mise
      - uses: jdx/mise-action@v3

      - name: Install dependencies
        run: |
          mise run install # install theme dependency

      - name: Build
        run: |
          hugo --minify
